# Generated by Django 5.2.6 on 2025-10-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscore',
            name='predicted_score',
            field=models.IntegerField(default=0),
        ),
    ]
